### ISSUE TITLE
This Deployment has been disabled.

### ISSUE THREAD

**Issue by orivelton** [yoyocharlie/nextMotion#2]
- This Deployment has been disabled.

![Screenshot 2024-10-03 at 14 36 22](https://github.com/user-attachments/assets/f01a43a2-2db7-420b-83e5-2630456a6ba2)

**Comment by yoyocharlie** [comment]
Thanks for opening the issue. The deployment is on Vercel's free tier and because I had a large asset (mp4) being served, I apparently went 300% over the free tier's data transfer limit for the month 😅. We basically just have to wait out the remainder of the month to see the site go back up. In the meantime, I've removed the large asset that was eating up 95% of my data transfer allowance.
